# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

blank_issues_enabled: false
contact_links:
  - name: ğŸ’ IOHK Technical Support
    url: https://iohk.zendesk.com/hc/en-us
    about: |
      Users: Please feel welcome to ask for help from the IOHK
      Technical Support Desk. They are knowledgeable about commonly
      experienced issues and workarounds.
  - name: ğŸ—© Cardano Forums
    url: https://forum.cardano.org/
    about: |
      General discussion about Cardano and `cardano-wallet`.
  - name: ğŸ—© Cardano Forums - Developers
    url: https://forum.cardano.org/c/developers/29
    about: |
      If you are an application developer seeking assistance with
      using `cardano-wallet` or its associated APIs, please use the
      Developers category of the Cardano forums.
  - name: Security issues
    url: mailto:security@iohk.io
    about: Please report security vulnerabilities here.
